### ISSUE TITLE
Global types

### ISSUE THREAD

**Issue by swsnr** [gjsify/gnome-shell#12]
On startup GNOME Shell creates a few globals and monkey-patches some standard classes, see https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/environment.js

Notably, it

1. adds a global `global = Shell.Global.get()`,
2. adds gettext functions to the global namespace (though using these appears to be discouraged; at least I've never seen anyone using those in extensions),
3. monkey-patches the standard `String` to add the `format` function from `imports.Format.format`, and
4. monkey-patches the standard `Math` object to add a `clamp` function.

I think these type definitions should mirror those (though 2. is probably debatable), i.e. include these globals in the ambient index module.

I can provide a pull request for these environment types, but I'm unsure where to add a corresponding ambient declaration file, as I haven't really grasped how the final module files are generated by the build scripts 🤔

**Comment by schnz** [comment]
Take this with a grain of salt, since I am also not very familiar with the build scripts. But from what I can tell, this should work:

### Step 1
`packages/gnome-shell/src/global.d.ts`:

```ts
import Shell from "@girs/shell-13";

declare global {
  const global: Shell.Global;
}

interface Math {
  /**
   * Returns {@link x} clamped to the inclusive range of {@link min} and {@link max}.
   * @see https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/8a8539ee6766058b39d0a5c0961a08f76799f4da/js/ui/environment.js#L357
   *
   * @param x The value to be clamped.
   * @param min The lower bound of the result.
   * @param max The upper bound of the result.
   */
  clamp(x: number, min: number, max: number): number;
}

// [...] further declarations as you see fit
```

### Step 2
In `packages/gnome-shell/scripts/generate-exports.js`, `packages/gnome-shell/scripts/generate-files.js`, and `packages/gnome-shell/scripts/generate-index.js`  you can add `global.d.ts` to the `IGNORE_FILENAMES` array. This prevents that the d.ts file is exported as gnome resource module etc.

Run **`yarn run build`**. The `global.d.ts` file should be part of the `dist` folder now and can be imported/referenced from downstream projects.

---

I haven't gave this much thought. @JumpLink does know the architecture alot better than I do :)

**Comment by JumpLink** [comment]
Thank you very much, I will look at this in detail as soon as possible

**Comment by swsnr** [comment]
@JumpLink @schnz I've opened https://github.com/gjsify/gnome-shell/pull/13 for this 🙂

**Comment by Freed-Wu** [comment]
> The global.d.ts file should be part of the dist folder now

However, [the document](https://github.com/gjsify/gnome-shell/tree/main/packages/gnome-shell#gnome-shell-globals) still said `import '@girs/gnome-shell/extensions/global';` not `import '@girs/gnome-shell/dist/extensions/global';`
