### ISSUE TITLE
Gnome 45: How to move forward?

### ISSUE THREAD

**Issue by schnz** [gjsify/gnome-shell#5]
**Preamble**
I am currently in the process of rewriting a Gnome shell extension and the breaking changes of Gnome 45 were the trigger for this. I am not the author of the original extension and I am a total newbie on the subject, although I learned alot within the last few days.

The typings you provide here (and [here](https://github.com/gjsify/types)) are _very_ useful for a type safe and productive development. I wonder how anyone could write a complex extension without them. However, they are currently targeting Gnome 44 from what I can tell.

**Matter at hand**
I have used [ts-for-gir](https://github.com/gjsify/ts-for-gir) to create Gnome 45 compatible typings and also created a package for the `gnome-shell` essentially by forking this repository and performing a search replace for the imports (adapting the `version=` query). And.... et voilà: I've got phenomenal types for the most part with only a few custom declarations or re-exports required for the `gnome-shell` package.

I like the idea of distributing an npm package for everyone to use, so I came here. Creating a PR would be a matter of minutes, but I am not really sure what's the best approach in terms of versioning and possible backports. Essentially I see two options:

**Option A: Lifecycle Policy**
The first option would be to have separate branches such as `gnome44`, `gnome45`, etc. Each branch contains the typings for the targeting Gnome environment and of course only depends on `@gjsify/<lib>` packages that are compatible with this release. This way it would be possible to provide backports whenever typings are improved but at the cost of a higher maintenance overhead. Therefore I propose to put a time limit for backporting of improvements for older Gnome versions (e.g. for 2 years after release).

**Option B: Evergreen Policy**
The second option would be to simply keep the typings up-to-date with the latest Gnome release and simply publish a new NPM package (ideally with matching versioning) each time. This also means that bugfixes and improvements of types for older Gnome versions wouldn't really be an option (unless they are tracked in separate branches, but then I would go for option A).

---

I would be happy to go with either of the two options. Maybe there are more options that I am not seeing. I would appreciate feedback from you @JumpLink (or any other contributor/maintainer, if any). Maybe you could also address which approach you would favor for the `gjsify/types` repository. From what I can tell, Gnome 44 and Gnome 45 packages could live side-by-side from one another as of now. If that is guaranteed to be the case for future releases as well, that would be perfect.

**Comment by Totto16** [comment]
Hey @schnz Do you have a link / repo for the types, since I am also rewriting a massive Extension and it is pain atm. I managed to fix some types, that I specifically need, but thats not a clean solution, the best atm would be, to just create a PR and imo it's best to create separate branches, and than publish separate version to npm, so that we have 
e.g. `@girs/gnome-shell@44.0.0` and than in the next bugfix o that `@girs/gnome-shell@44.0.1`  etc.
and a separate maintained version for `@girs/gnome-shell@45.0.0`. So that Gnome 44 and Gnome 45 type are supported.

Anywhere, that's just my opinon.

**Comment by schnz** [comment]
Hey @Totto16 ,

> Do you have a link / repo for the types

I do. Check my repository at https://github.com/schnz/gTile/tree/types . The `dist` directory holds the tarballs. You can also install the packages through the [GitHub NPM registry](https://github.com/schnz?tab=packages). Note that you should configure `npm` accordingly:

npm.rc
```
//npm.pkg.github.com/:_authToken=<redacted>
@schnz:registry=https://npm.pkg.github.com
```
Even though the packages are public, GitLab requires you to authenticate with the registry. Check their [documentation](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#authenticating-with-a-personal-access-token) for more information. Note that I have only created the types that were necessary for the extension at hand. But see if it fits your need.

> the best atm would be, to just create a PR and imo it's best to create separate branches, and than publish separate version to npm

There will be separate versions for the npm package either way. The question is whether or not to maintain multiple branches. I don't know the ecosystem well enough to know whether it is worth it. Judging from the [download history](https://www.npmjs.com/package/@girs/gnome-shell) thats probably not the case.


P.S. You might want to add  some glue code to make the `resource://` imports work. A little excerpt from my typings:

`/gnome-shell.d.ts`
```
/// <reference path="./node_modules/@schnz/gjs/dom.d.ts" />

declare module "resource:///org/gnome/shell/ui/panelMenu.js" {
  import * as ns from "@schnz/gnome-shell/src/ui/panelMenu.d.ts";

  export = ns;
}

declare module "resource:///org/gnome/shell/ui/popupMenu.js" {
  import * as ns from "@schnz/gnome-shell/src/ui/popupMenu.js";

  export = ns;
}

declare module "resource:///org/gnome/shell/ui/main.js" {
  import * as ns from "@schnz/gnome-shell/src/ui/main.d.ts";

  export = ns;
}
```

**Comment by Totto16** [comment]
@schnz Thanks

Yes, the most extensions are unfortunately written in js 😓 

We use rollup to rewrite the imports, so no problems there 👍🏼

**Comment by JumpLink** [comment]
Hi [@schnz, @Totto16, and other contributors],

Thank you for your valuable insights and suggestions regarding the GNOME Shell 45 migration. I'm currently managing this project in my spare time, which limits my availability, but I'm committed to making progress as soon as possible.

I've already started migrating to GNOME Shell 45 and have managed to get the example running under this version. Furthermore, I've updated all dependent `@girs/xyz` types to their current versions and outlined the next TODOs in the README. Your contributions, especially in writing more types manually, would be incredibly helpful. Most of the types I've written are untested and might be outdated, so any assistance in this area would be greatly appreciated.

Regarding the options for versioning and possible backports mentioned in the comments, I'm still evaluating the best approach. I'll make sure to thoroughly review the issue and all comments to better understand your perspectives and suggestions. It's been a pleasant surprise to see the project gain followers, and I apologize for any oversight regarding the issues raised. I'm committed to improving my engagement with the community.

I believe with the foundational elements now in place, we can continue to advance the project effectively. Any further collaboration, especially in areas like testing and updating the types, would be a significant boost.

Looking forward to your continued support and contributions.

**Comment by JumpLink** [comment]
I wanted to add something important. It would be awesome if some of you could step in as contributors or even as maintainers. This would really help take some of the load off, especially since my free time is pretty tight with personal stuff going on.

Having more maintainers would mean we're not just waiting for my schedule to clear up to get things moving. It’s all about teamwork, right? If you’re into overseeing parts of the project, reviewing pull requests, or just want to help steer the ship, that would be super helpful.

If you’re up for it, or know someone who might be, give me a shout. It could make a world of difference and keep this project rolling.

Thanks a ton for all your understanding and support!

Cheers,
JumpLink

**Comment by schnz** [comment]
Hey @JumpLink ,

thanks for the response. How sad,. I hoped for an update and hosted the Gnome 45 compatible typings only in the GitHub npm registry which requires authentication. 3 days ago I prepared the public release of the extension I was rewriting and that required all npm dependencies to be [publicly available](https://www.npmjs.com/org/gtile). Now I see that 2 days ago you published an update on your own. Unfortunate timing, but I am still glad that (part) of the update is available now.

Regarding the `gnome-shell` types: I noticed that they are not 100% up-to-date, but only because it lacked some exports, not because the existing exports were faulty. I only added the missing types that I required specifically for the extension at hand https://github.com/gTile/gTile/blob/master/gnome-shell.d.ts. The gnome-shell project is relatively large and I didn't wanted to invest a lot of time to add types that I don't need anyway.

As to your most recent post: I could imagine to be a contributor/maintainer. But I also want to say that my primary interest would be to have up-to-date types for the extension that I rewrote. So I would certainly be able to update the `gisify/types` repository once a new Gnome version releases. But to be honest I don't see myself making large efforts towards completing the `gnome-shell` types. But I could/will certainly contribute the types that I now added to the `gnome-shell.d.ts` that I linked above.

**Comment by JumpLink** [comment]
Hey @schnz,

Totally get it if you're only contributing types that you need for your work. That's actually a great approach because it means those types are getting tested in real-world scenarios. If more folks did the same, we'd gradually build up a solid collection of types, covering the most commonly used ones.

So, definitely, even smaller contributions are super valuable and much appreciated. 

Once I knock out the key TODOs, I'm planning to roll out a new NPM release tagged as version 45.0.0.

**Comment by Totto16** [comment]
I also am willing to help, but as @schnz mentioned, doing the whole GNOME Shell types is much work, I also only use a subset of them, so I'll look into my self written ones, and if there's some new stuff in there, that isn't covered by already existing types or types in the PR I'll be happy to also make a PR with those types. I would also think that option B ("evergreen updates") is better. The main problem I see in general, that soooo many extensions are made in js and not in TS. I also have experience with some EGO reviewers, that are against versioned imports. e.g [here](https://github.com/oae/gnome-shell-pano/pull/222#issuecomment-1812213024) 

```
import Clutter from 'gi://Clutter?version=13'
```
So thats a really bad view on types, since than it theoretically can load everything, and the types are not that helpful, if we load v 14, where potential breaking changes can occur, like e.g. this time in Clutter v12 vs. v13.

And just asking since I have not that much knowledge abut gnome-shell development yet, are there no .gir or .typelib files for gnome shell?

**Comment by JumpLink** [comment]
> And just asking since I have not that much knowledge abut gnome-shell development yet, are there no .gir or .typelib files for gnome shell?

No, because parts of the gnome shell are written in Javascript itself. However, they are working on better JSDoc support so that the types can be derived better and better. Maybe we can even generate types automatically thanks to JSDoc?

**Comment by JumpLink** [comment]
Sorry I don't answer which option I prefer, I am also for Option B. We could create branches for older Gnome Shell versions before we port this project to a new version to keep Option A open, e.g. for the case someone is willing to do this work

**Comment by JumpLink** [comment]
@Totto16 , @schnz I have now automated some of the work so that only the types need to be defined, the rest is now generated automatically. I have updated the README.md where I describe this in more detail. I have also created some new types (blind). By the way, ChatGPT can be very helpful, even if the types usually have to be reworked by hand, here you can have a look at my [history with ChatGPT](https://chat.openai.com/share/e3c95c78-5203-4560-9ee2-62ed6c95e22d).

If there is a need I can make a beta release on NPM. I would be very happy if you could test it.

**Comment by Totto16** [comment]
Tanks you, I'll look into them since I yesterday looked at my gnome-shell types, and I thought I didn't have so much, but it were  more than I thought, so I'm definitely going to test those and submit changes / addition if needed ❤️

**Comment by schnz** [comment]
> I have now automated some of the work so that only the types need to be defined, the rest is now generated automatically. I have updated the README.md where I describe this in more detail. I have also created some new types (blind).

Works perfectly well, thank you! Going to submit the PR now (your updates already provided some of the missing types).

Very impressive what ChatGPT is already able to do, although I am not really sure how this is more helpful than [built-in TSC](https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html#tsconfig) functionality.

Also going to close this, as you answered and implemented all I asked in my initial request :).

> If there is a need I can make a beta release on NPM. I would be very happy if you could test it.

If you release a beta package after my (to be opened) PR is merged, I would be happy to directly depend on the @gjsify packages for gTile!

**Comment by JumpLink** [comment]
@schnz version `45.0.0-beta1` is published now 👍
